name: Baboom
favicon: null
layout_spectrum: 0.5390982618555427
typography_spectrum: 0.11659342609345913
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.6433823392726481
  lightness: 0.3614301490597427
  saturation: 0.40115858148783445
  rhythmicContrast: 0.3798623769544065
purpose: []
