name: Baboom
favicon: null
layout_spectrum: 0.5390982618555427
typography_spectrum: 0.11659342609345913
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcf4eb'
    - '#ead0d2'
    - '#846061'
    - '#080302'
    - '#392124'
  brandStrength: 0.625
  lightness: 0.875
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
